-- CreateEnum
CREATE TYPE "genre" AS ENUM ('AUTOBIOGRAPHY', 'BIOGRAPHY', 'FANTASY', 'FICTION', 'HISTORICAL_FICTION', 'HORROR', 'MYSTERY', 'POETRY', 'ROMANCE', 'SCIENCE_FICTION', 'SELF_HELP', 'THRILLER');

-- AlterTable
ALTER TABLE "book" ADD COLUMN     "genre" "genre"[];
